apps/cadastros/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import *


app_name = 'cadastros'


urlpatterns = [
    path('create-jogador', login_required(CreateJogador.as_view()), name='new_jogador'),
    path('list-jogador', login_required(ListJogador.as_view()), name='list_jogador'),
    path('detail-jogador/<int:pk>/', login_required(DetailJogador.as_view()), name='detail_jogador'),
]

apps/gerencia/urls.py
from django.urls import path
from .views import *


app_name = 'gerencia'


urlpatterns = [
    path('scores-jogador/<int:id>/', JogadorScores, name='detail_score'),
    path('graficos/<int:id>/', grafico, name='grafic_jogador'),
    path('new-score', login_required(CreateScore.as_view()), name='new_score'),
    path('new-especifico', login_required(CreateEspecifico.as_view()), name='new_especifico'),
    path('detail-especifico/<int:pk>/', login_required(DetailEspecifico.as_view()), name='detail_especifico'),
]

gerencia_time/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cadastros/', include('apps.cadastros.urls')),
    path('gerencia/', include('apps.gerencia.urls')),
    path('', include('apps.core.urls')),
    path('accounts', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#personalização da template admin
admin.site.site_title = 'Gerenciador'
admin.site.site_header = 'Murici-FC'

apps/cadastros/models.py
from django.db import models
from django.urls import reverse_lazy


class Jogador(models.Model):
    posicao_choice = {
        ('Go', 'Goleiro'),
        ('Le', 'Lateral Esquerdo'),
        ('La', 'Lateral Direito'),
        ('Ze', 'Zagueiro Esquerdo'),
        ('Zd', 'Zagueiro Direito'),
        ('V', 'Primeiro Volante'),
        ('Vm', 'Segundo Volante'),
        ('Me', 'Meia Esquerda'),
        ('Md', 'Meia Direita'),
        ('Mc', 'Meia Central'),
        ('Ata_d', 'Atacante Direita'),
        ('Ata_e', 'Atacante Esquerda'),
        ('Ce', 'Centroavante')
    }
    nome = models.CharField('Nome', max_length=100)
    idade = models.IntegerField('Idade')
    posicao = models.CharField('Posicao', max_length=17, choices=posicao_choice, default='')
    posicao_opcao = models.CharField('Posicao_opcao', null=True, blank=True, max_length=17, choices=posicao_choice)
    cpf = models.CharField('CPF', max_length=14)
    foto = models.FileField(upload_to='media/%y/%m/%d/', null=True, blank=True)
    #SCORES
    erro_passe = models.IntegerField('Erros de passes', default=0)
    media_erro_passe = models.FloatField('Média de passes errados', default=0)
    acerto_passe_curto = models.IntegerField('Passes curtos', default=0)
    media_acert_pass_curt = models.FloatField('Média de passes curtos', default=0)
    acerto_passe_longo = models.IntegerField('Passes longos', default=0)
    media_acert_pass_long = models.FloatField('Média de passes longos', default=0)
    gols = models.IntegerField('Gols', default=0)
    media_gols = models.FloatField('Média de gols', default=0)
    desarmes = models.IntegerField('Desarmes', default=0)
    media_desarmes = models.FloatField('Média de desarmes', default=0)
    defesas = models.IntegerField('Defesas', default=0)
    media_defesas = models.FloatField('Média de defesas', default=0)
    passes_gol = models.IntegerField('Passes pra gol', default=0)
    media_pass_gol = models.FloatField('Média de passes pra gol', default=0)
    faltas = models.IntegerField('Faltas', default=0)
    media_faltas = models.FloatField('Média de faltas', default=0)
    cartao_amarelo = models.IntegerField('Cartão Amarelo', default=0)
    media_cart_amar = models.FloatField('Média de cartões amarelos', default=0)
    cartao_vermelho = models.IntegerField('Cartão vermelho', default=0)
    media_cart_verm = models.FloatField('Média de cartões vermelhos', default=0)
    partidas = models.IntegerField(default=0)

    def __str__(self):
        return '%s - %s' % (self.nome, self.posicao)

    def get_absolute_url(self):
        return reverse_lazy('cadastros:list_jogador')

    class Meta:
        verbose_name = 'Jogador'
        verbose_name_plural = 'Jogadores'

apps/cadastros/views.py
from django.shortcuts import render, redirect
from .models import *
from apps.gerencia.models import Especifico
from django.views.generic import CreateView, ListView,\
    UpdateView, DetailView, DeleteView


class CreateJogador(CreateView):
    model = Jogador
    fields = ['nome', 'idade', 'posicao', 'posicao_opcao',
              'cpf', 'foto']


class ListJogador(ListView):
    model = Jogador
    # paginate_by = 100


class DetailJogador(DetailView):
    model = Jogador

apps/cadastros/templates/cadastros/jogador_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<header class="detail">
   <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Jogador</th>
        <th scope="col">Posição</th>
        <th scope="col">Posição Opcional</th>
        <th scope="col">Idade</th>
        <th scope="col">Foto</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>{{object.nome}}</td>
        <td>{{object.posicao}}</td>
        <td>{{object.posicao_opcao}}</td>
        <td>{{object.idade}}</td>
        <td><img src="{{object.foto.url}}"  alt="foto jogador" class="img-jogador"></td>
      </tr>
    </tbody>
  </table>
</header>
{% endblock %}

apps/cadastros/templates/cadastros/jogador_form.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap %}
{% block content %}

<header class="cadastro">
    <div class="container">
        <form method="post" enctype="multipart/form-data">{% csrf_token %}
            {{ form|bootstrap }}
            <div class="cadastro-button">
                <button type="submit">Confirmar</button>
                <button type="reset">Cancelar</button>
            </div>
        </form>
    </div>
</header>
{% endblock %}

apps/cadastros/templates/cadastros/jogador_list.html
{% extends 'base.html' %}
{% block content %}
<header class="cadastro">
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th></th>
        <th scope="col">Jogador</th>
        <th scope="col">Idade</th>
        <th scope="col">Posição</th>
        <th scope="col">Posição Opcional</th>
        <th scope="col">Score Partida</th>
      </tr>
    </thead>
    <tbody>
    {% for form in object_list  %}
      <tr>
        <td><img src="{{form.foto.url}}"  alt="foto jogador" class="img-jogador"></td>
        <td><a href="{% url 'gerencia:detail_especifico' form.pk %}">{{form.nome}}</a></td>
        <td>{{form.idade}}</td>
        <td>{{form.posicao}}</td>
        <td>{{form.posicao_opcao}}</td>
        <td><a href="{% url 'gerencia:detail_score' form.pk %}"><i class="bi bi-card-checklist"><svg
                xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                class="bi bi-card-checklist" viewBox="0 0 16 16">
              <path d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1
              .5-.5h13zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5
               1.5 0 0 0 14.5 2h-13z"/>
              <path d="M7 5.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm-1.496-.854a.5.5 0
               0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0l-.5-.5a.5.5 0 1 1 .708-.708l.146.147 1.146-1.147a.5.5 0 0 1
              .708 0zM7 9.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm-1.496-.854a.5.5 0 0 1 0
               .708l-1.5 1.5a.5.5 0 0 1-.708 0l-.5-.5a.5.5 0 0 1 .708-.708l.146.147 1.146-1.147a.5.5 0 0 1 .708 0z"/>
            </svg></i></a></td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</header>
{% endblock %}