apps/cadastros/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import *


app_name = 'cadastros'


urlpatterns = [
    path('create-jogador', login_required(CreateJogador.as_view()), name='new_jogador'),
    path('list-jogador', login_required(ListJogador.as_view()), name='list_jogador'),
    path('detail-jogador/<int:pk>/', login_required(DetailJogador.as_view()), name='detail_jogador'),
]

apps/core/urls.py
from django.urls import path
from .views import *

app_name = 'core'

urlpatterns = [
    path('', home, name='home'),
]

apps/gerencia/urls.py
from django.urls import path
from .views import *


app_name = 'gerencia'


urlpatterns = [
    path('scores-jogador/<int:id>/', JogadorScores, name='detail_score'),
    path('graficos/<int:id>/', grafico, name='grafic_jogador'),
    path('new-score', login_required(CreateScore.as_view()), name='new_score'),
    path('new-especifico', login_required(CreateEspecifico.as_view()), name='new_especifico'),
    path('detail-especifico/<int:pk>/', login_required(DetailEspecifico.as_view()), name='detail_especifico'),
]

gerencia_time/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cadastros/', include('apps.cadastros.urls')),
    path('gerencia/', include('apps.gerencia.urls')),
    path('', include('apps.core.urls')),
    path('accounts', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#personalização da template admin
admin.site.site_title = 'Gerenciador'
admin.site.site_header = 'Murici-FC'

templates/base.html
{% load static %}
<html>
    <head>
       <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css"
             rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl"
             crossorigin="anonymous">
       <link rel="stylesheet" href="{% static 'css/stilo.css' %}">
       <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'core:home' %}">TIME-FC</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#conteudoNavbarSuportado"
                aria-controls="conteudoNavbarSuportado" aria-expanded="false" aria-label="Alterna navegação">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="conteudoNavbarSuportado">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'cadastros:new_jogador' %}">Cadastro Jogador
                  <span class="sr-only"></span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'cadastros:list_jogador' %}">Plantel</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'gerencia:new_score' %}">Scores</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'gerencia:new_especifico' %}">Dados Específicos</a>
            </li>
            <li class="user">
              <a class="nav-link" href="{% url 'logout' %}">logout</a>
            </li>
          </ul>
        </div>
      </nav>
        {% block content %}{% endblock %}
    </body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
               integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
               crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
 </html>